blogfunciones/applications/blog/urls.py
from django.contrib import admin
from django.urls import path


from .import views
from .views import home,generales,programacion,tutoriales,detallePost

app_name = "blog_app"
urlpatterns = [

    path('',home,name="index"),
    path('generales/',generales,name="generales"),
    path('programacion/',programacion,name="programacion"),
    path('tutoriales/',tutoriales,name="tutoriales"),
    path('<slug:slug>',detallePost,name="detalle_post"),

]

blogfunciones/blogfunciones/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('applications.blog.urls')),
    # re_path('',include('applications.autor.urls')),
    # re_path('',include('applications.lector.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogfunciones/applications/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField('nombre de la categoria', max_length=50,null=False,blank=False)
    estado = models.BooleanField('categoria activada/categoria no activada',default=True)
    fecha_creacion = models.DateField('fecha de creacion', auto_now=False, auto_now_add=True)


    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.nombre

class Autor(models.Model):

    id = models.AutoField(primary_key=True)
    nombre = models.CharField('nombre de autor', max_length=150,null=False,blank=False)
    apellidos = models.CharField('apellidos de autor', max_length=150,null=False,blank=False)
    facebook = models.URLField('facebook', max_length=300,null=True,blank=True)
    twitter = models.URLField('twitter', max_length=300,null=True,blank=True)
    instagram = models.URLField('instagram', max_length=300,null=True,blank=True)
    web = models.URLField('web', max_length=300,null=True,blank=True)
    correo = models.EmailField('correo electronico', max_length=254,blank=False,null=False)
    estado = models.BooleanField('autor activo/autor no activo')
    fecha_creacion = models.DateField('fecha de creacion', auto_now=False, auto_now_add=True)


    class Meta:

        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'

    def __str__(self):
        return  "{0},{1}".format(self.apellidos,self.nombre)


class Post(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField('Titulo', max_length=90,blank=False,null=False)
    slug = models.CharField('Slug', max_length=50,blank=False,null=False)
    descripcion = models.CharField('Descripcion', max_length=50,blank=False,null=False)
    contenido = RichTextField()
    imagen = models.URLField(max_length=255,blank=False,null=False)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    estado = models.BooleanField('Publicado/No Publicado',default=True)
    fecha_creacion = models.DateField('Fecha de Creacion', auto_now=False, auto_now_add=True)

    class Meta:

        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.titulo

blogfunciones/applications/blog/views.py
from django.shortcuts import render
from django.http import Http404
from django.db.models import Q
from django.core.paginator import Paginator



# Create your views here.

from .models import Post,Autor,Categoria

def home(request):
    queryset=request.GET.get("buscar")
    print(f"la consulta es: {queryset}")
    post=Post.objects.filter(estado=True)
    if queryset:
        post=Post.objects.filter(
            Q(titulo__icontains=queryset) |
            Q(descripcion__icontains=queryset)
        ).distinct()

    contexto={'contexto_post':post}

    paginator=Paginator(post,2)
    page=request.GET.get('page')
    post=Paginator

    return render(request,'index.html',contexto)


def detallePost(request,slug):
    try:
        post=Post.objects.get(
            slug=slug
            )
        contexto={'detalle_post':post}
        return render(request,'post.html',contexto)
    except Post.DoesNotExist:
        raise Http404


def generales(request):
    post=Post.objects.filter(
        estado=True,
        categoria=Categoria.objects.get(nombre__iexact='General')
        )
    contexto={'contexto_post':post}
    return render(request,'generales.html',contexto)

def programacion(request):
    post=Post.objects.filter(
    estado=True,
    categoria=Categoria.objects.get(nombre__iexact='Programacion')
    )
    contexto={'contexto_post':post}
    return render(request,'programacion.html',contexto)

def tutoriales(request):
    post=Post.objects.filter(
    estado=True,
    categoria=Categoria.objects.get(nombre__iexact='Tutorial')
    )
    contexto={'contexto_post':post}
    return render(request,'tutoriales.html',contexto)

blogfunciones/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}
      </title>

    <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}">
</head>
<body>
    <!-- <h3>esta es la base</h3> -->

<nav class="navbar bg-primary navbar-expand-lg navbar-dark" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'blog_app:index' %}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item active"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog_app:index' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog_app:generales' %}">Generales</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog_app:programacion' %}">Programacion</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog_app:tutoriales' %}">Tutoriales</a></li>
            </ul>
        </div>
    </div>
</nav>


        {% block content %}
        {% endblock content %}


    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#!">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; 2024</div>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static './js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

blogfunciones/templates/generales.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
Generales
{% endblock title %}

{% block titulo_principal %}
Posts Generales
{% endblock titulo_principal %}

{% block imagen %}
    {% static 'img/generales.jpg' %}
{% endblock imagen %}

blogfunciones/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<header>
    <div class="overlay">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1 class="text-center">
                        {% block titulo_principal %}
                            Bienvenido al Blog
                        {% endblock titulo_principal %}
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row py-3">
        <div class="col-md-12 search">
            <form action="" method="get">
                <div id="custom-search-input">
                    <div class="input-group col-md-12">
                        <input type="text"class="form-control" id="buscar" name="buscar">
                        <span class="input-group-list">
                                <button type="submit" class="btn btn-success">Buscar</button>
                        </span>

                    </div>

                </div>
            </form>
        </div>


    </div>
</div>

<div class="carousel-item active">
    <img class="d-block w-100"  src="{% block imagen %}{% static 'img/home-bg.jpg' %}{% endblock imagen %}"  alt="Firste slid">
    <div class="carousel-caption d-none d-md-block">
</div>

<!-- {% block contenido_new %} -->

<div class="container px-4 py-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <!-- Post preview-->
            {% if contexto_post %}
            {% for a in contexto_post %}
            <div class="post-preview">
                <a href="{% url 'blog_app:detalle_post' a.slug %}">
                    <h2 class="post-title">{{a.titulo}}</h2>
                    <h3 class="post-subtitle">{{a.descripcion}}</h3>
                </a>
                <p class="post-meta">
                   <strong>{{a.autor}}</strong>
                    {{a.fecha_creacion}}
                </p>
                <hr class="my-4" />
            </div>
            {% endfor %}
            {% else %}
            <h1 class="display-1">no hay posts registrados</h1>
            {% endif %}
        </div>
    </div>
</div>
<!-- {% endblock contenido_new %} -->

{% endblock content %}

blogfunciones/templates/post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{detalle_post.titulo}}
{% endblock title %}

<img class="d-block w-100"  src=""  alt="Firste slid">

{% block content %}

<div class="container">
    <div class="row">
        <div class="">
            <h1 class="text-center py-4">{{detalle_post.titulo}}</h1>
        </div>
        <div class="">
            <img  class="mx-auto d-block"  src="{{detalle_post.imagen}}"  alt="Firste slid">
        </div>

            <div class="text-justify">
            <p>
                {{detalle_post.contenido | safe}}
            </p>
            </div>
            <div class="post-preview">
                <h4 class="post-subtitle">Categoria: {{detalle_post.categoria}}</h4>
                <p class="post-meta">
                   <strong>{{detalle_post.autor}}</strong>
                    {{detalle_post.fecha_creacion}}
                </p>
                <hr class="my-4" />
            </div>
    </div>
</div>


{% endblock content %}

blogfunciones/templates/programacion.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
Programacion
{% endblock title %}

{% block titulo_principal %}
Post de Programacion
{% endblock titulo_principal %}

<hr>
{{contexto_post.all}}
<hr>
{% block imagen %}
    {% static 'img/programacion.jpg' %}
{% endblock imagen %}

blogfunciones/templates/tutoriales.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
Tutoriales
{% endblock title %}

{% block titulo_principal %}
Post de Tutoriales
{% endblock titulo_principal %}

{% block imagen %}
    {% static 'img/tutoriales.jpg' %}
{% endblock imagen %}